apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: traefik
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/instance: traefik
      app.kubernetes.io/name: traefik
